### ISSUE TITLE
Permission denied when cloning

### ISSUE THREAD

**Issue by olaven** [michalholasek/monkey-lang#1]
__issule__: 
When I use the `clone`-command in `README.md`, I get `permission denied`

__workaround__: 
using `https://github.com/michalholasek/monkey-lang.git`instead. 

If this applies to more people, it may be an idea to update the readme 😄 

Have a nice day!

**Comment by michalholasek** [comment]
Thank you for pointing that out, fixed in https://github.com/michalholasek/monkey-lang/commit/6b7d1af56278e340458c2a8752a60f4fdafb2765.
